# Generated by Django 4.2.1 on 2023-05-27 18:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_alter_place_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
